stages:
  - push

variables:
  IMAGE_NAME: aminerachyd/sdtd
  DOCKERHUB_ACCESS_TOKEN_RACHYD: ${DOCKERHUB_ACCESS_TOKEN_RACHYD}

push:
  stage: push
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u aminerachyd -p $DOCKERHUB_ACCESS_TOKEN_RACHYD
    - docker build . -t $IMAGE_NAME
    - docker push $IMAGE_NAME

