- become: yes
  hosts: all
  tasks:
    - name: Init Kubeadm
      shell: sudo kubeadm init

    - name: Create .kube directory
      file:
        path: /home/amine/.kube
        state: directory

    - name: Copy k8s configuration to .kube dir
      shell: sudo cp -i /etc/kubernetes/admin.conf /home/amine/.kube/config

    - name: Change ownership of .kube config
      shell: sudo chown amine:amine /home/amine/.kube/config

    - name: Install network plugin
      shell: sudo -u amine kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

    - name: Generate join command
      command: sudo kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command
      become: false
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
