pvt_key = "~/.ssh/id_rsa"
pub_key = "~/.ssh/id_rsa.pub"
ssh_username = "amine"
project = "projet-sdtd"
project_region = "us-central1"
project_zone = "us-central1-c"
docker_playbook = "docker_playbook.yml"
k8s_playbook = "k8s_playbook.yml"
kubeadm_master_playbook = "kubeadm_master_playbook.yml"

